Added workflow for security file check (#37)

diff --git a/.github/workflows/onpullrequest.yml b/.github/workflows/onpullrequest.yml
--- a/.github/workflows/onpullrequest.yml
+++ b/.github/workflows/onpullrequest.yml
@@ -12,21 +12,29 @@ on:
 permissions: read-all
 
 jobs:
+
+  security-file-check:
+    runs-on: [ ubuntu-20.04 ]
+    steps:
+      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+        with:
+          fetch-depth: 0
+
+      - name: Check Security.md file
+        run: |
+          if [ ! -f ./security.md ]; then
+            echo "Security.md file is missing"
+            exit 1
+          fi
+          
   build-test:
     runs-on: [ ubuntu-20.04 ]
+    needs: [ "security-file-check" ]
     env:
       http_proxy: ${{ secrets.HTTP_PROXY }}
       https_proxy: ${{ secrets.HTTPS_PROXY }}
       no_proxy: ${{ secrets.NO_PROXY }}
     steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
-        with:
-          egress-policy: audit
-
-      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
-        with:
-          fetch-depth: 0
 
       - name: Setup Java JDK
         uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
